"""fix equipment status naming collision

Revision ID: 0f6321c8815d
Revises: cb0607407bb7
Create Date: 2026-05-13 20:15:18.385719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f6321c8815d'
down_revision: Union[str, Sequence[str], None] = 'cb0607407bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment_components')
    op.drop_table('anomaly_tickets')
    op.add_column('equipment', sa.Column('last_heartbeat', sa.DateTime(), nullable=True))
    op.add_column('equipment', sa.Column('connectivity_status', sa.String(), nullable=False))
    op.alter_column('equipment_telemetry', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('idx_telemetry_equipment_time'), table_name='equipment_telemetry')
    op.create_index(op.f('ix_equipment_telemetry_created_at'), 'equipment_telemetry', ['created_at'], unique=False)
    op.create_index(op.f('ix_equipment_telemetry_equipment_id'), 'equipment_telemetry', ['equipment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipment_telemetry_equipment_id'), table_name='equipment_telemetry')
    op.drop_index(op.f('ix_equipment_telemetry_created_at'), table_name='equipment_telemetry')
    op.create_index(op.f('idx_telemetry_equipment_time'), 'equipment_telemetry', ['equipment_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('equipment_telemetry', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('equipment', 'connectivity_status')
    op.drop_column('equipment', 'last_heartbeat')
    op.create_table('anomaly_tickets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('equipment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('severity', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metric_snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'open'::text"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('anomaly_tickets_pkey'))
    )
    op.create_table('equipment_components',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('equipment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('serial_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('equipment_components_equipment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('equipment_components_pkey'))
    )
    # ### end Alembic commands ###
