"""add cost breakdown to service_orders

Revision ID: 3fe9b6fbc8c5
Revises: a7884635e611
Create Date: 2026-05-02 10:47:02.771830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fe9b6fbc8c5'
down_revision: Union[str, Sequence[str], None] = 'a7884635e611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_orders', sa.Column('estimated_material_cost', sa.Float(), nullable=True))
    op.add_column('service_orders', sa.Column('estimated_labor_cost', sa.Float(), nullable=True))
    op.add_column('service_orders', sa.Column('actual_material_cost', sa.Float(), nullable=True))
    op.add_column('service_orders', sa.Column('actual_labor_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_orders', 'actual_labor_cost')
    op.drop_column('service_orders', 'actual_material_cost')
    op.drop_column('service_orders', 'estimated_labor_cost')
    op.drop_column('service_orders', 'estimated_material_cost')
    # ### end Alembic commands ###
