"""customer location enterprise fields

Revision ID: 4105f6f6a73f
Revises: ed2b7c434f65
Create Date: 2026-05-20 19:50:28.337576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4105f6f6a73f'
down_revision: Union[str, Sequence[str], None] = 'ed2b7c434f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_locations', 'sla_tier',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'STANDARD'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_locations', 'sla_tier',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'STANDARD'::character varying"))
    # ### end Alembic commands ###
