"""add customer contacts and addresses

Revision ID: 572cafe01014
Revises: 84b45bb271b5
Create Date: 2026-05-20 15:58:22.293891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '572cafe01014'
down_revision: Union[str, Sequence[str], None] = '84b45bb271b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('equipment_components', sa.Column('maintenance_log_id', sa.UUID(), nullable=True))
    op.add_column('equipment_components', sa.Column('component_type', sa.String(length=100), nullable=False))
    op.add_column('equipment_components', sa.Column('component_name', sa.String(length=255), nullable=False))
    op.add_column('equipment_components', sa.Column('manufacturer', sa.String(length=255), nullable=True))
    op.add_column('equipment_components', sa.Column('model_number', sa.String(length=255), nullable=True))
    op.add_column('equipment_components', sa.Column('installation_date', sa.Date(), nullable=True))
    op.add_column('equipment_components', sa.Column('replacement_date', sa.Date(), nullable=True))
    op.add_column('equipment_components', sa.Column('warranty_expiration', sa.Date(), nullable=True))
    op.add_column('equipment_components', sa.Column('useful_life_months', sa.String(length=50), nullable=True))
    op.add_column('equipment_components', sa.Column('failure_reason', sa.Text(), nullable=True))
    op.add_column('equipment_components', sa.Column('replacement_reason', sa.Text(), nullable=True))
    op.add_column('equipment_components', sa.Column('is_critical', sa.Boolean(), nullable=False))
    op.alter_column('equipment_components', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'equipment_components', 'maintenance_logs', ['maintenance_log_id'], ['id'], ondelete='SET NULL')
    op.drop_column('equipment_components', 'name')
    op.drop_column('equipment_components', 'brand')
    op.drop_column('equipment_components', 'model')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment_components', sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('equipment_components', sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('equipment_components', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'equipment_components', type_='foreignkey')
    op.alter_column('equipment_components', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('equipment_components', 'is_critical')
    op.drop_column('equipment_components', 'replacement_reason')
    op.drop_column('equipment_components', 'failure_reason')
    op.drop_column('equipment_components', 'useful_life_months')
    op.drop_column('equipment_components', 'warranty_expiration')
    op.drop_column('equipment_components', 'replacement_date')
    op.drop_column('equipment_components', 'installation_date')
    op.drop_column('equipment_components', 'model_number')
    op.drop_column('equipment_components', 'manufacturer')
    op.drop_column('equipment_components', 'component_name')
    op.drop_column('equipment_components', 'component_type')
    op.drop_column('equipment_components', 'maintenance_log_id')
    op.drop_table('customer_contacts')
    op.drop_table('customer_addresses')
    # ### end Alembic commands ###
