"""edit city to service_order

Revision ID: 6e1d26e250d8
Revises: fd40fef9fcaa
Create Date: 2026-04-25 23:41:41.008477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e1d26e250d8'
down_revision: Union[str, Sequence[str], None] = 'fd40fef9fcaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_order_tasks', sa.Column('is_done', sa.Boolean(), nullable=True))
    op.drop_column('service_order_tasks', 'is_completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_order_tasks', sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('service_order_tasks', 'is_done')
    # ### end Alembic commands ###
