"""add category_id to equipment_types

Revision ID: 84b45bb271b5
Revises: a1ed6173d393
Create Date: 2026-05-17 20:46:08.075034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84b45bb271b5'
down_revision: Union[str, Sequence[str], None] = 'a1ed6173d393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_components',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_plan_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('maintenance_plan_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['maintenance_plan_id'], ['maintenance_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_plan_tasks_maintenance_plan_id'), 'maintenance_plan_tasks', ['maintenance_plan_id'], unique=False)
    op.create_table('equipment_measurements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('maintenance_log_id', sa.UUID(), nullable=False),
    sa.Column('measurement_type', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['maintenance_log_id'], ['maintenance_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('equipment_brands_name_key'), 'equipment_brands', type_='unique')
    op.create_unique_constraint(None, 'equipment_categories', ['code'])
    op.alter_column('equipment_types', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('maintenance_plan_equipment', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('maintenance_plan_equipment', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_unique_constraint('uq_pm_plan_equipment', 'maintenance_plan_equipment', ['maintenance_plan_id', 'equipment_id'])
    op.alter_column('maintenance_plans', 'last_run_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('maintenance_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('maintenance_plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_maintenance_plans_active'), 'maintenance_plans', ['active'], unique=False)
    op.create_index(op.f('ix_maintenance_plans_next_run_date'), 'maintenance_plans', ['next_run_date'], unique=False)
    op.add_column('maintenance_task_templates', sa.Column('requires_photo', sa.Boolean(), nullable=True))
    op.add_column('maintenance_task_templates', sa.Column('requires_measurement', sa.Boolean(), nullable=True))
    op.add_column('maintenance_task_templates', sa.Column('requires_pass_fail', sa.Boolean(), nullable=True))
    op.add_column('maintenance_task_templates', sa.Column('measurement_unit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maintenance_task_templates', 'measurement_unit')
    op.drop_column('maintenance_task_templates', 'requires_pass_fail')
    op.drop_column('maintenance_task_templates', 'requires_measurement')
    op.drop_column('maintenance_task_templates', 'requires_photo')
    op.drop_index(op.f('ix_maintenance_plans_next_run_date'), table_name='maintenance_plans')
    op.drop_index(op.f('ix_maintenance_plans_active'), table_name='maintenance_plans')
    op.alter_column('maintenance_plans', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('maintenance_plans', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('maintenance_plans', 'last_run_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint('uq_pm_plan_equipment', 'maintenance_plan_equipment', type_='unique')
    op.drop_column('maintenance_plan_equipment', 'created_at')
    op.drop_column('maintenance_plan_equipment', 'active')
    op.alter_column('equipment_types', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'equipment_categories', type_='unique')
    op.create_unique_constraint(op.f('equipment_brands_name_key'), 'equipment_brands', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_table('equipment_measurements')
    op.drop_index(op.f('ix_maintenance_plan_tasks_maintenance_plan_id'), table_name='maintenance_plan_tasks')
    op.drop_table('maintenance_plan_tasks')
    op.drop_table('equipment_components')
    # ### end Alembic commands ###
