"""equipment module

Revision ID: 84d671fd2c37
Revises: aa70ab3a14dd
Create Date: 2026-05-08 19:14:46.344328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84d671fd2c37'
down_revision: Union[str, Sequence[str], None] = 'aa70ab3a14dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_orders', 'status',
               existing_type=postgresql.ENUM('draft', 'pending', 'assigned', 'in_progress', 'paused', 'completed', 'cancelled', name='service_order_status'),
               nullable=False)
    op.drop_column('service_orders', 'priority')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_orders', sa.Column('priority', postgresql.ENUM('low', 'medium', 'high', 'urgent', name='serviceorderpriority'), autoincrement=False, nullable=True))
    op.alter_column('service_orders', 'status',
               existing_type=postgresql.ENUM('draft', 'pending', 'assigned', 'in_progress', 'paused', 'completed', 'cancelled', name='service_order_status'),
               nullable=True)
    # ### end Alembic commands ###
