"""inventory movements

Revision ID: 86c4cb3075f4
Revises: 6e1d26e250d8
Create Date: 2026-04-26 21:05:55.992674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86c4cb3075f4'
down_revision: Union[str, Sequence[str], None] = '6e1d26e250d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('stock', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('min_stock', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('inventory_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('service_order_materials', sa.Column('inventory_item_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'service_order_materials', 'inventory_items', ['inventory_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_order_materials', type_='foreignkey')
    op.drop_column('service_order_materials', 'inventory_item_id')
    op.drop_table('inventory_movements')
    op.drop_table('inventory_items')
    # ### end Alembic commands ###
