"""customer location enterprise fields

Revision ID: 9f6ee21f75f9
Revises: 4105f6f6a73f
Create Date: 2026-05-20 20:05:46.989826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f6ee21f75f9'
down_revision: Union[str, Sequence[str], None] = '4105f6f6a73f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_locations', 'sla_tier',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'STANDARD'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_locations', 'sla_tier',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'STANDARD'::character varying"))
    # ### end Alembic commands ###
