"""add city to customers

Revision ID: a7884635e611
Revises: 8d26e4ad10a8
Create Date: 2026-05-01 19:33:10.093504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7884635e611'
down_revision: Union[str, Sequence[str], None] = '8d26e4ad10a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('city', sa.String(), nullable=True))
    op.drop_index(op.f('idx_assignments_user'), table_name='service_order_assignments')
    op.drop_index(op.f('idx_service_orders_scheduled_at'), table_name='service_orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_service_orders_scheduled_at'), 'service_orders', ['scheduled_at'], unique=False)
    op.create_index(op.f('idx_assignments_user'), 'service_order_assignments', ['user_id'], unique=False)
    op.drop_column('customers', 'city')
    # ### end Alembic commands ###
