"""stabilize_maintenance_domain

Revision ID: e404b3234151
Revises: ebebd20f6389
Create Date: 2026-05-13 22:02:24.375855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e404b3234151'
down_revision: Union[str, Sequence[str], None] = 'ebebd20f6389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    maintenance_plan_type = postgresql.ENUM(
        'preventive',
        'inspection',
        'predictive',
        name='maintenance_plan_type'
    )

    maintenance_plan_type.create(op.get_bind())

    work_order_source = postgresql.ENUM(
        'manual',
        'preventive_maintenance',
        'inspection',
        'predictive',
        'emergency',
        name='work_order_source'
    )

    work_order_source.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_locations', sa.Column('location_type', sa.String(), nullable=True))
    op.add_column('customer_locations', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('equipment', sa.Column('physical_location', sa.String(), nullable=True))
    op.drop_column('equipment', 'equipment_location')
    op.add_column('maintenance_plans', sa.Column('plan_type', sa.Enum('preventive', 'inspection', 'predictive', name='maintenance_plan_type'), nullable=False))
    op.add_column(
        'service_orders',
        sa.Column(
            'source',
            sa.Enum(
                'manual',
                'preventive_maintenance',
                'inspection',
                'predictive',
                'emergency',
                name='work_order_source'
            ),
            nullable=False,
            server_default='manual'
        )
    )
    op.add_column('service_orders', sa.Column('customer_location_id', sa.UUID(), nullable=True))
    op.add_column('service_orders', sa.Column('equipment_id', sa.UUID(), nullable=True))
    op.add_column('service_orders', sa.Column('maintenance_plan_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_service_orders_customer_location_id'), 'service_orders', ['customer_location_id'], unique=False)
    op.create_index(op.f('ix_service_orders_equipment_id'), 'service_orders', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_service_orders_maintenance_plan_id'), 'service_orders', ['maintenance_plan_id'], unique=False)
    op.create_foreign_key(None, 'service_orders', 'equipment', ['equipment_id'], ['id'])
    op.create_foreign_key(None, 'service_orders', 'maintenance_plans', ['maintenance_plan_id'], ['id'])
    op.create_foreign_key(None, 'service_orders', 'customer_locations', ['customer_location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    maintenance_plan_type = postgresql.ENUM(
        'preventive',
        'inspection',
        'predictive',
        name='maintenance_plan_type'
    )

    work_order_source = postgresql.ENUM(
        'manual',
        'preventive_maintenance',
        'inspection',
        'predictive',
        'emergency',
        name='work_order_source'
    )

    work_order_source.drop(op.get_bind())

    maintenance_plan_type.drop(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_orders', type_='foreignkey')
    op.drop_constraint(None, 'service_orders', type_='foreignkey')
    op.drop_constraint(None, 'service_orders', type_='foreignkey')
    op.drop_index(op.f('ix_service_orders_maintenance_plan_id'), table_name='service_orders')
    op.drop_index(op.f('ix_service_orders_equipment_id'), table_name='service_orders')
    op.drop_index(op.f('ix_service_orders_customer_location_id'), table_name='service_orders')
    op.drop_column('service_orders', 'maintenance_plan_id')
    op.drop_column('service_orders', 'equipment_id')
    op.drop_column('service_orders', 'customer_location_id')
    op.drop_column('service_orders', 'source')
    op.drop_column('maintenance_plans', 'plan_type')
    op.add_column('equipment', sa.Column('equipment_location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('equipment', 'physical_location')
    op.drop_column('customer_locations', 'is_active')
    op.drop_column('customer_locations', 'location_type')
    # ### end Alembic commands ###
