"""add maintenance_log_id to equipment_photos

Revision ID: e62732457b66
Revises: 372926df469b
Create Date: 2026-05-09 20:28:32.184404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e62732457b66'
down_revision: Union[str, Sequence[str], None] = '372926df469b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment_photos', sa.Column('maintenance_log_id', sa.UUID(), nullable=True))
    op.add_column('equipment_photos', sa.Column('file_path', sa.String(), nullable=False))
    op.add_column('equipment_photos', sa.Column('description', sa.String(), nullable=True))
    op.create_foreign_key(None, 'equipment_photos', 'maintenance_logs', ['maintenance_log_id'], ['id'])
    op.drop_column('equipment_photos', 'photo_path')
    op.drop_column('equipment_photos', 'uploaded_at')
    op.add_column('maintenance_logs', sa.Column('equipment_condition', sa.String(), nullable=True))
    op.add_column('maintenance_logs', sa.Column('refrigerant_added', sa.String(), nullable=True))
    op.add_column('maintenance_logs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('maintenance_logs', 'technician_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('maintenance_logs_equipment_id_fkey'), 'maintenance_logs', type_='foreignkey')
    op.create_foreign_key(None, 'maintenance_logs', 'equipment', ['equipment_id'], ['id'], ondelete='CASCADE')
    op.drop_column('maintenance_logs', 'performed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_logs', sa.Column('performed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'maintenance_logs', type_='foreignkey')
    op.create_foreign_key(op.f('maintenance_logs_equipment_id_fkey'), 'maintenance_logs', 'equipment', ['equipment_id'], ['id'])
    op.alter_column('maintenance_logs', 'technician_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('maintenance_logs', 'created_at')
    op.drop_column('maintenance_logs', 'refrigerant_added')
    op.drop_column('maintenance_logs', 'equipment_condition')
    op.add_column('equipment_photos', sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('equipment_photos', sa.Column('photo_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'equipment_photos', type_='foreignkey')
    op.drop_column('equipment_photos', 'description')
    op.drop_column('equipment_photos', 'file_path')
    op.drop_column('equipment_photos', 'maintenance_log_id')
    # ### end Alembic commands ###
