"""maintenance architecture stabilization

Revision ID: ebebd20f6389
Revises: 0f6321c8815d
Create Date: 2026-05-13 20:55:17.670980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebebd20f6389'
down_revision: Union[str, Sequence[str], None] = '0f6321c8815d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_order_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('maintenance_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('frequency_days', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('next_run_date', sa.Date(), nullable=True),
    sa.Column('auto_generate_work_orders', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['customer_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_plans_customer_id'), 'maintenance_plans', ['customer_id'], unique=False)
    op.create_index(op.f('ix_maintenance_plans_location_id'), 'maintenance_plans', ['location_id'], unique=False)
    op.create_table('maintenance_plan_equipment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('maintenance_plan_id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['maintenance_plan_id'], ['maintenance_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_plan_equipment_equipment_id'), 'maintenance_plan_equipment', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_maintenance_plan_equipment_maintenance_plan_id'), 'maintenance_plan_equipment', ['maintenance_plan_id'], unique=False)
    op.create_table('maintenance_task_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('maintenance_plan_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['maintenance_plan_id'], ['maintenance_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_task_templates_maintenance_plan_id'), 'maintenance_task_templates', ['maintenance_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_task_templates_maintenance_plan_id'), table_name='maintenance_task_templates')
    op.drop_table('maintenance_task_templates')
    op.drop_index(op.f('ix_maintenance_plan_equipment_maintenance_plan_id'), table_name='maintenance_plan_equipment')
    op.drop_index(op.f('ix_maintenance_plan_equipment_equipment_id'), table_name='maintenance_plan_equipment')
    op.drop_table('maintenance_plan_equipment')
    op.drop_index(op.f('ix_maintenance_plans_location_id'), table_name='maintenance_plans')
    op.drop_index(op.f('ix_maintenance_plans_customer_id'), table_name='maintenance_plans')
    op.drop_table('maintenance_plans')
    op.drop_table('work_order_sources')
    # ### end Alembic commands ###
