"""add cost breakdown to service_orders2

Revision ID: f74909f236e3
Revises: 3fe9b6fbc8c5
Create Date: 2026-05-02 11:21:09.401990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f74909f236e3'
down_revision: Union[str, Sequence[str], None] = '3fe9b6fbc8c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_orders', sa.Column('labor_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_orders', 'labor_cost')
    # ### end Alembic commands ###
